version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_URL=mongodb://db:27017/list
      - APP_PORT=3000
    ports: ["3000:3000"]
  db:
    container_name: db
    image: mongo
    restart: always
